import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import '@/app/globals.scss'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="synthwave">
      <body className={`${nunito.className} antialiased`}>{children}</body>
    </html>
  )
}
